### ISSUE TITLE
allow renewable tokens?

### ISSUE THREAD

**Issue by joemiller** [hashicorp/vault-plugin-secrets-kubernetes#17]
In some cases it would be desirable to have renewable tokens. Is there a reason this backend does not support renewable tokens?

**Comment by tvoran** [comment]
Hi @joemiller, we'd be curious to know more about your use cases! In general this engine can't really renew an existing token since the expiration is part of the JWT.

**Comment by joemiller** [comment]
@tvoran Ah, that makes sense 🤦 

The use case I have in mind is to replace a pattern where a KSA token is copied from a k8s Secret created by the service-account controller and put it into vault's KV engine for other apps to access.

What I did not realize is that those tokens look different and lack an `exp`, ex:

```json
{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "default",
  "kubernetes.io/serviceaccount/secret.name": "my-ksa-token-zsmpp",
  "kubernetes.io/serviceaccount/service-account.name": "my-ksa",
  "kubernetes.io/serviceaccount/service-account.uid": "666687a-33c4-4291-8a7a-a5dc123c99e4",
  "sub": "system:serviceaccount:default:my-ksa"
}
```

-vs- a JWT created by the secrets/kubernetes backend:
```json
{
  "aud": [
    "https://kubernetes.default.svc"
  ],
  "exp": 1670444200,
  "iat": 1670440600,
  "iss": "https://oidc.eks.us-east-1.amazonaws.com/id/REDACTED",
  "kubernetes.io": {
    "namespace": "default",
    "serviceaccount": {
      "name": "my-ksa",
      "uid": "666687a-33c4-4291-8a7a-a5dc123c99e4"
    }
  },
  "nbf": 1670440600,
  "sub": "system:serviceaccount:default:my-ksa"
}
```

But since our goal is to remove forever tokens the tokens issued with an expiration are better.

**Comment by tvoran** [comment]
Thanks for bringing it up! Closing for now.
